"""
Tool integrations for the Research Paper Agent.

Wraps Tavily search with the retry framework.
Follows the existing _tavily_search() pattern (bwa_backend.py L164-184).
"""

from __future__ import annotations

import os
import logging
from typing import List

from research_paper_agent.errors import retry_with_backoff, RetryableError
from research_paper_agent.config import RETRY_SEARCH

logger = logging.getLogger("research_paper_agent")


# ── Tavily Search (with retry) ───────────────────────────────────────

@retry_with_backoff(
    max_retries=RETRY_SEARCH["max_retries"],
    base_delay=RETRY_SEARCH["base_delay"],
    max_delay=RETRY_SEARCH["max_delay"],
    jitter=RETRY_SEARCH["jitter"],
    retryable_exceptions=(RetryableError, TimeoutError, ConnectionError, OSError),
)
def _tavily_search_inner(query: str, max_results: int = 6) -> List[dict]:
    """Raw Tavily call — retried by the decorator."""
    from langchain_community.tools.tavily_search import TavilySearchResults  # type: ignore

    tool = TavilySearchResults(max_results=max_results)
    results = tool.invoke({"query": query})

    normalised: List[dict] = []
    for r in results or []:
        normalised.append({
            "title": r.get("title") or "",
            "url": r.get("url") or "",
            "snippet": r.get("content") or r.get("snippet") or "",
            "published_at": r.get("published_date") or r.get("published_at"),
            "source": r.get("source"),
        })
    return normalised


def tavily_search(query: str, max_results: int = 6) -> List[dict]:
    """
    Safe wrapper — returns [] on any failure (existing fallback pattern).
    """
    import time
    from research_paper_agent.cost_tracker import get_current_tracker

    if not os.getenv("TAVILY_API_KEY"):
        logger.warning("[tavily] TAVILY_API_KEY not set — returning empty results")
        return []
    t0 = time.perf_counter()
    try:
        results = _tavily_search_inner(query, max_results=max_results)
        duration = time.perf_counter() - t0
        get_current_tracker().record_tool_call(
            tool_name="tavily_search",
            node_name="literature_worker",
            latency_seconds=duration,
            call_type="search",
        )
        return results
    except Exception as exc:
        duration = time.perf_counter() - t0
        logger.error("[tavily] Search failed for query=%r: %s", query, exc)
        return []


# ── Gemini Image Generation ──────────────────────────────────────────
# Follows the existing _gemini_generate_image_bytes() pattern
# (bwa_backend.py L428-473)

@retry_with_backoff(
    max_retries=1,
    base_delay=2.0,
    max_delay=4.0,
    jitter=False,
    retryable_exceptions=(RetryableError, TimeoutError, ConnectionError, OSError),
)
def gemini_generate_image_bytes(prompt: str) -> bytes:
    """
    Returns raw image bytes generated by Gemini.
    Requires: pip install google-genai
    Env var: GOOGLE_API_KEY
    """
    from google import genai
    from google.genai import types

    import time
    from research_paper_agent.cost_tracker import get_current_tracker

    api_key = os.environ.get("GOOGLE_API_KEY")
    if not api_key:
        raise RuntimeError("GOOGLE_API_KEY is not set.")

    t0 = time.perf_counter()
    client = genai.Client(api_key=api_key)

    resp = client.models.generate_content(
        model="gemini-2.5-flash-image",
        contents=prompt,
        config=types.GenerateContentConfig(
            response_modalities=["IMAGE"],
            safety_settings=[
                types.SafetySetting(
                    category="HARM_CATEGORY_DANGEROUS_CONTENT",
                    threshold="BLOCK_ONLY_HIGH",
                )
            ],
        ),
    )
    duration = time.perf_counter() - t0
    get_current_tracker().record_tool_call(
        tool_name="gemini-2.5-flash-image",
        node_name="figure_generator",
        latency_seconds=duration,
        call_type="image",
    )

    # Depending on SDK version, parts may hang off resp.candidates[0].content.parts
    parts = getattr(resp, "parts", None)
    if not parts and getattr(resp, "candidates", None):
        try:
            parts = resp.candidates[0].content.parts
        except Exception:
            parts = None

    if not parts:
        raise RuntimeError("No image content returned (safety/quota/SDK change).")

    for part in parts:
        inline = getattr(part, "inline_data", None)
        if inline and getattr(inline, "data", None):
            return inline.data

    raise RuntimeError("No inline image bytes found in response.")
